CUDA_VISIBLE_DEVICES=$1 python train_script/inference/simulator_llama4drive.py \
--planner self_model/checkpoint-2100 \
--base_model llama2/llama-2-13b-chat-hf \
--planner_type llama4drive_lora_ins_wo_stop \
--save_dir asyncdriver_inter_$3 \
--ins_wo_stop \
--short_ins 30 \
--lora_r 8 \
--type $2 \
--llm_inf_step $3 \
--simulation_root_path simulation_save_root_path \